### ISSUE TITLE
Статус первого выпуска (вне TEHGAM)

### ISSUE THREAD

**Issue by Tourorist** [TEHGAM/ADR#318]
**Что осталось сделать:**
* [x] Синхронизировать копию правил (#291, #292)
* [x] Довести до ума игровые сообщения (#306)
* [x] Перевести журнал изменений на английский (#309)
* [x] Доработать логотип миссии (#310)
  * Если возражений нет, то с названием уже разобрались.
* [ ] Сформулировать общие правила и задачи форка (#313)
* [ ] Подготовить сам текст выпуска для [Armaholic](http://www.armaholic.com/), [BIF](http://forums.bistudio.com/) и [Steam Workshop](http://steamcommunity.com/app/107410/workshop/) (#319).

Это касаемо подачи <kbd>v3.5</kbd>, а что уже в неё войдёт в плане исправлений и дополнений это решать всем вам кто этим занимается.

Начну ставить свои галочки со второй недели после Нового года, планирую справиться за месяц. То есть, с моей стороны, в первых числах февраля уже можно будет выпускать, если с вашей всё будет готово.

**Comment by Tourorist** [comment]
* ```[1/6]```Пока я только думал с какой задачи начать, @Noart537 уже умудрился журнал перевести.

**Comment by Noart537** [comment]
Какую следующую задачу будем выполнять?

**Comment by tym32167** [comment]
@Noart537 
Смотри по приоритету (количеству звездочек). Чем больше звездочек, тем важнее задача.Я бы предложил #293

**Comment by Tourorist** [comment]
@Noart537. если ты имеешь ввиду по моим личным задачам, то спасибо конечно за предложение, но @tym32167 прав — у вас тот звездопад поважней этих будет.

Как начну отставать от графика то буду уже просить у вас помощи по конкретным пунктам. Пока справляюсь, просто отвлекся немного на RHS.

**Comment by Noart537** [comment]
Я как на работу выйду, то активно займусь звездочками и др. задачами. Сейчас пока хочется отдыхать и проводить время не только у компа. ;)

**Comment by Tourorist** [comment]
Вычёркиваю задачу по Правилам — помимо меня, три человека кое-как да проверили.

**Comment by Tourorist** [comment]
На выходных доработаю и переведу README касательно предпоследней задачи, и к понедельнику уже постараюсь написать текст выпуска.
